court/urls.py
from django.urls import path
from . import views 
app_name = "court"

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('register/',views.UserFormView.as_view(),name='register'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('judge/', views.JudgeView.as_view(), name='judge'),
    path('advocate/', views.AdvocateView.as_view(), name='advocate'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('fileCase/', views.FileCase.as_view(), name='fileCase'),
    path('feecalc/', views.FeesFormView.as_view(), name='feecalc'),
    path('search/', views.search, name='search'),
    path('status/', views.SearchView.as_view(), name='status'),
    path('judge/case/<int:pk>/verdict/', views.VerdictView.as_view(), name='caseverdict'),
    # path('search/', views.search, name='search'),
]

ecourt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('court.urls')),
]

court/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from multiselectfield import MultiSelectField
from django.core.validators import MaxValueValidator
from django.core.validators import MinValueValidator

CHOICES = [
    ("Judge", "Judge"),
    ("Lawyer", "Lawyer"),
]

Court_Type=[
    ("SUP","Supreme Court"),
    ("HIG","High Court"),
    ("DST","District Court"),
    ("SES","Session Court"),
]

Case_type=[
    ("CIV","Civil"),
    ("CRI","Criminal"),
]

Verdict_type=[
    ("Guilty","Guilty"),
    ("Not-Guilty","Not-Guilty")
]
def user_directory_path(instance, filename): 
    # file will be uploaded to MEDIA_ROOT / user_<id>/<filename> 
    return 'user_{0}/{1}'.format(instance.user.id, filename) 

class UserProfile(models.Model):
    # required by the auth model
    user = models.OneToOneField(User, unique=True, on_delete=models.CASCADE)
    user_type = models.CharField(max_length=30, choices=CHOICES)


@receiver(post_save, sender=User)
def create_profile(sender, instance, created, **kwargs):
    """Create a matching profile whenever a user object is created."""
    if created:
        profile, new = UserProfile.objects.get_or_create(user=instance)

class Advocate(models.Model):
    license_no = models.CharField(max_length=17, primary_key=True)
    name=models.CharField(max_length=400)
    address=models.CharField(max_length=500)
    court_type=MultiSelectField(choices=Court_Type,max_length=20)
    #contact_number=models.BigIntegerField(null=True)
    user = models.ForeignKey(User,on_delete=models.CASCADE)

    def __str__(self):
        return self.name

class Judge(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE, null=True)
    name=models.CharField(max_length=100)
    court_type=models.CharField(choices=Court_Type,max_length=20)
    district=models.CharField(max_length=500)
    license_no = models.CharField(max_length=17, primary_key=True)
    
class Case(models.Model):
    advocate=models.ForeignKey(User,on_delete=models.CASCADE,related_name="advocate_user")
    name_of_applicant=models.CharField(max_length=400)
    address=models.CharField(max_length=500)
    phone_number=models.BigIntegerField(null=True, blank=True)
    case_type=models.CharField(max_length=3,choices=Case_type)
    court_type=models.CharField(choices=Court_Type,max_length=3)
    subject=models.CharField(max_length=500)
    file=models.FileField(upload_to=user_directory_path, blank=True, null=True)
    cnr=models.CharField(max_length=16, unique=True, blank=True,null=True)
    fileNo=models.CharField(max_length=16, unique=True, blank=True,null=True)
    status=models.BooleanField(default=False)
    district=models.CharField(max_length=100,blank=True,null=True)
    state=models.CharField(max_length=100,blank=True,null=True)
    name_of_respondent=models.CharField(max_length=400,null=True)
    lawyer_of_respondent=models.CharField(max_length=400,null=True)
    address_of_respondent=models.CharField(max_length=500, null=True)
    file_date=models.DateField(auto_now=True, blank=True, null=True)
    judge=models.ForeignKey(Judge,on_delete=models.CASCADE,related_name="judge_user",null=True,blank=True)
    verdict=models.CharField(choices=Verdict_type,max_length=10,blank=True,null=True)
    hearing_date=models.DateField(blank=True, null=True)
    hr=models.BooleanField(default=False, null=True,blank=True)

    def __str__(self):
        return self.cnr


# Create your models here.

court/forms.py
from django.contrib.auth.models import User
from django import forms
from .models import *

CHOICES = [
    ("Judge", "Judge"),
    ("Lawyer", "Lawyer"),
]
Court_Type=[
    ("SUP","Supreme Court"),
    ("HIG","High Court"),
    ("DST","District Court"),
    ("SES","Session Court"),
]

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    password1 = forms.CharField(widget=forms.PasswordInput)
    user_type = forms.ChoiceField(choices=CHOICES)
    court = forms.MultipleChoiceField(choices = Court_Type,required=True,widget=forms.CheckboxSelectMultiple)
    address = forms.CharField(max_length=500, required=True)
    license_no = forms.CharField(min_length=15, max_length=17, required=True)

    class Meta:
        model = User
        fields = [
            "username",
            "password",
            "password1",
            "email",
            "first_name",
            "last_name",
            "user_type",
            "court",
            "address",
            "license_no",
        ]


class LoginForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ["username", "password"]

class CaseForm(forms.ModelForm):

    class Meta:
        model = Case
        fields = [
            "advocate",
            "name_of_applicant",
            "phone_number",
            "address",
            "case_type",
            "court_type",
            "subject",
            "file",
            "district",
            "state",
            "name_of_respondent",
            "lawyer_of_respondent",
            "address_of_respondent",
        ]
       
        exclude = ('advocate','status','cnr','fileNo','judge','file_date')


class SearchForm(forms.ModelForm):
    cnr=forms.CharField(max_length=16, required=True)
    class Meta:
        model = Case
        fields=[
            "cnr",
        ]

class FeesForm(forms.Form):
    court = forms.CharField(max_length=50)
    case = forms.CharField(max_length=50)
    subtype = forms.CharField(max_length=50)

class VerdictForm(forms.ModelForm):
    class Meta:
        model = Case
        fields = [
            "verdict",
        ]

court/views.py
from django.shortcuts import render
from django.views.generic import *
from django.views.generic.edit import *
from .models import *
from django.urls import reverse_lazy, reverse
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from .forms import *
from django.http import HttpResponseRedirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.contrib import messages
import random, string, datetime, time
from court.utils import get_judge, get_hearingdate
from django.db.models import Q


def generateKey():
    x = ''.join(random.choice(string.ascii_uppercase + string.ascii_lowercase + string.digits) for _ in range(16))
    return x

def generateNo():
    x = ''.join(random.choice(string.digits) for _ in range(8))
    return x    

class UserFormView(View):
    form_class = UserForm
    template_name = "court/registration_form.html"

    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {"form": form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            password1 = form.cleaned_data["password1"]
            first_name = form.cleaned_data["first_name"]
            last_name = form.cleaned_data["last_name"]
            user_type = form.cleaned_data["user_type"]
            court = form.cleaned_data["court"]
            address = form.cleaned_data["address"]
            license_no = form.cleaned_data["license_no"]

            if password == password1:
                if user_type=="Lawyer":
                    user.set_password(password)
                    user.save()
                    user = User.objects.get(username=username)
                    user_profile = UserProfile.objects.get(user=user)
                    user_profile.user_type = user_type
                    user_profile.save()
                    advocate_details=Advocate()
                    advocate_details.user=user
                    advocate_details.license_no=license_no
                    advocate_details.name=first_name+last_name
                    advocate_details.court_type=court
                    advocate_details.address=address
                    advocate_details.save()
                    messages.success(request, "Account register successfully")
                    return redirect("court:login")
                elif user_type=="Judge":
                    user.set_password(password)
                    user.save()
                    user = User.objects.get(username=username)
                    user_profile = UserProfile.objects.get(user=user)
                    user_profile.user_type = user_type
                    user_profile.save()
                    judge_details=Judge()
                    judge_details.user=user
                    judge_details.license_no=license_no
                    judge_details.name=first_name+last_name
                    judge_details.court_type=' '.join(map(str, court))
                    judge_details.district=address
                    judge_details.save()
                    messages.success(request, "Account register successfully")
                    return redirect("court:login")
                else: 
                    messages.success(request, "Wrong user type")
            else:
                messages.success(request, "Password does not match")
        else:
            return render(request, self.template_name, {"form": form})


class LoginView(View):
    form_class = LoginForm
    template_name = "court/login.html"

    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {"form": form})

    def post(self, request):
        form = self.form_class(request.POST)
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                user_profile=UserProfile.objects.get(user=request.user)
                #print(user_profile)
                user_type=user_profile.user_type
                #print(user_type)
                if user_type=="Lawyer":
                    return redirect("court:advocate")
                elif user_type=="Judge":
                    return redirect("court:judge")
                else:
                    return redirect("court:login",{"Wrong User Type"})

                # messages.info(request, 'Your have successfully loged in!')git              
            else:
                return render(
                    request,
                    "court/login.html",
                    {"error_message": "Your account has been disabled"},
                )
        else:
            return render(
                request,
                "court/login.html",
                {"form": form, "error_message": "Invalid login"},
            )

# class JudgeView(View):
#     form_class = LoginForm
#     template_name = "court/judge.html"

#     def get(self, request):
#         form = self.form_class(None)
#         return render(request, self.template_name, {"form": form})

# class AdvocateView(View):
#     form_class = LoginForm
#     template_name = "court/advocate.html"

#     def get(self, request):
#         form = self.form_class(None)
#         return render(request, self.template_name, {"form": form})

class FileCase(LoginRequiredMixin,View):
    form_class=CaseForm
    template_name='court/fileCase.html'
        
    def get(self,request):
        form=self.form_class(None)
        return render(request,self.template_name,{'form':form})

    def post(self,request):
        form=self.form_class(request.POST)
        if form.is_valid():
            provider=form.save(commit=False)
            phone_number=form.cleaned_data["phone_number"]
            if phone_number>=6000000000 and phone_number<=9999999999:
                form.instance.advocate = self.request.user
                form.instance.cnr=generateKey()
                form.instance.fileNo=generateNo()
                print(form.instance.court_type)
                print(form.instance.district)
                form.instance.judge=get_judge(form.instance.court_type,form.instance.district)
                form.instance.hearing_date=get_hearingdate()
                provider.save()
                return redirect("court:advocate")
            
        else:
            return render(request,self.template_name,{'form':form})

class LogoutView(View):
    form_class = LoginForm
    template_name = "court/login.html"

    def get(self, request):
        form = self.form_class(None)
        logout(request)
        return redirect(reverse("court:login"))

# class SearchView(ListView):
#     template_name = 'court/status.html'
#     context_object_name = "case_details"
#     model = Case

#     def get_queryset(self):
#         cnr = self.kwargs.get('cnr', '')
#         object_list = self.model.objects.all()
#         if cnr:
#             object_list = object_list.filter(cnr__icontains=cnr)
#         print(object_list)
#         return object_list

class SearchView(ListView):
    template_name = 'court/status.html'
    context_object_name = "case_details"
    model = Case

    def get_queryset(self):
       result = super(SearchView, self).get_queryset()
       query = self.request.GET.get('search')
       if query:
          postresult = Case.objects.filter(cnr__icontains=query)
          result = postresult
       else:
           result = None
       return result

class AdvocateView(ListView):
    template_name = 'court/advocate.html'
    context_object_name = "case_details"
    model = Case

    def hearing_reminder(self,qsf):
        for case in qsf:
            hd = case.hearing_date - datetime.timedelta(days=1)
            curdate = datetime.datetime.today()
            if (hd.day == curdate.day and hd.month == curdate.month and hd.year == curdate.year):
                case.hr = True

    def get_queryset(self):
        qs = super().get_queryset()
        user = self.request.user
        if user is None:
            print(0)
            return None
        qsf = qs.filter(advocate=user)
        self.hearing_reminder(qsf)
        return qsf

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        queryset = Case.objects.filter(advocate=self.request.user)
        context['pending'] = queryset.filter(status=0).count()
        context['closed'] = queryset.filter(status=1).count()
        return context

class JudgeView(ListView):
    template_name = 'court/judge.html'
    context_object_name = "case_details"
    model = Case

    def hearing_reminder(self,qsf):
        for case in qsf:
            hd = case.hearing_date - datetime.timedelta(days=1)
            curdate = datetime.datetime.today()
            if (hd.day == curdate.day and hd.month == curdate.month and hd.year == curdate.year):
                case.hr = True

    #def schedulerrun(self,jqs):
    #    print("hr4")
    #    schedule.every().day.at("23:30").do(hearing_reminder)
    #    print("hr5")
    #    i=2
    #    while i:
    #        schedule.run_pending()
    #    print("hr6")
    
    def get_queryset(self):
        qs = super().get_queryset()
        j = Judge.objects.get(user=self.request.user)
        if j is None:
             print(0)
             return None
        qsf = qs.filter(judge=j)
        #schedule.every().day.at("23:30").do(hearing_reminder,qsf)
        self.hearing_reminder(qsf)
        return qsf

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

court/templates/court/advocate.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <title>E-Courts</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="{% static 'court/style_dashboard.css' %}">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>

<!--  Navbar  -->
<header class="navbar navbar-inverse navbar-fixed-top bs-docs-nav" role="banner">
  <div class="container">
    <div class="navbar-header">
      <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a href="./" class="navbar-brand">E-Courts</a>
    </div>
    <nav class="collapse navbar-collapse bs-navbar-collapse" role="navigation">
      <ul class="nav navbar-nav navbar-right">
        <li>
          <a href="{% url 'court:home' %}">Home</a>
        </li>
        <li>
          <a href="{% url 'court:about' %}">About</a>
        </li>
        <li>
          <a href="{% url 'court:feecalc' %}">Fee calculator</a>
        </li>
        <li>
          <a href="{% url 'court:status' %}">Check Status</a>
        </li>
        <li >
          <a href="{% url 'court:logout' %}">Logout</a>
        </li>
      </ul>
    </nav>
  </div>
</header><br /><br ><br >

<!-- nav bar ends here -->

<div class="container">
      <div id="myCarousel" class="carousel slide" data-ride="carousel">
        <!-- Indicators -->
        <ol class="carousel-indicators">
          <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
          <li data-target="#myCarousel" data-slide-to="1"></li>
          <li data-target="#myCarousel" data-slide-to="2"></li>
        </ol>
      </div>
</div>

<!-- Welcome Section -->
<h1 class="welcome">Welcome!</h1>
<table>
  <tr>
    <td><button type="submit" class="file"><a href="{% url 'court:fileCase' %}">File a case</a></button></td>
  </tr>
</table><br>
<table>
 <tr>   
<td>
  <button type="button" onclick="hdate()" class="file">&nbsp;Reminder&nbsp;</button>
<div id="reminder_hearing" style="display: none; margin-left: 180px;">
  <h3 id="remindhead"> Hearing(s) on {{case.hearing_date}}</h3>
  <h5 id="nohearing" style="display: none;">No hearings</h5>
  {% for case in case_details %}
  {% if case.hr %}
  <h5>File No.: {{case.fileNo}}&emsp;&emsp;{{case.name_of_applicant}} v. {{case.name_of_respondent}}</h5>
  <h5 id="dummy" style="display: none;"></h5>
  <script>
    document.getElementById("dummy").style.display="block";
  </script>
  {% else %}
  <script>
    x=document.getElementById("dummy");
    if(x.style.display=="none"){
      document.getElementById("nohearing").style.display="block";
    }
  </script>
  {% endif %}
  {% endfor %}
</div>
</td>
</tr>
</table>

<ul class="Nav-case">
    <li>Total Cases <br> <span class="num">{{ case_details.count }}</span></li>
    <li>Pending Cases<br> <span class="num">{{ pending }}</span></li>
    <li>Completed Cases<br> <span class="num">{{ closed }}</span></li>
</ul>

<table class="case-data" align="center">
<tr>
    <th class="case-data">CNR No.</th>
    <th class="case-data">File No.</th>
    <th class="case-data">Petitioner</th>
</tr>

{% for case in case_details %}
<tr>
    <td class="case-data">{{case.cnr}}</td>
    <td class="case-data">{{case.fileNo}}</td>
    <td class="case-data">{{case.name_of_applicant}}</td>
</tr>
{% endfor %}
<!-- <tr>
    <td class="case-data">123</td>
    <td class="case-data">456</td>
    <td class="case-data">Someone</td>
</tr>
<tr>
    <td class="case-data">123</td>
    <td class="case-data">456</td>
    <td class="case-data">Someone</td>
</tr>
<tr>
    <td class="case-data">123</td>
    <td class="case-data">456</td>
    <td class="case-data">Someone</td>
</tr>
<tr>
    <td class="case-data">123</td>
    <td class="case-data">456</td>
    <td class="case-data">Someone</td>
</tr>
<tr>
    <td class="case-data">123</td>
    <td class="case-data">456</td>
    <td class="case-data">Someone</td>
</tr>
<tr>
    <td class="case-data">123</td>
    <td class="case-data">456</td>
    <td class="case-data">Someone</td>
</tr> -->
</table><br><br>

<script>
  function hdate(){
    n =  new Date();
    y = n.getFullYear();
    m = n.getMonth() + 1;
    d = n.getDate();
    d=d+1;
    document.getElementById("remindhead").innerHTML="Hearing(s) on " + m + "/" + d + "/" + y;
    x=document.getElementById("reminder_hearing");
    if(x.style.display=="block"){
      x.style.display="none";
    }
    else if(x.style.display=="none"){
      x.style.display="block"
    }
  }
</script>

  <!-- Site footer -->
<hr><br>
<footer class="site-footer fix">
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-6">
        <h6>About</h6>
        <p class="text-justify"><i>TOWARDS A DIGITAL INDIA </i> The e-Courts project was conceptualized on the basis of the National Policy and Action Plan for Implementation of information and communication technology in the Indian Judiciary–2005 submitted by e-Committee, with a vision to transform the Indian Judiciary by ICT enablement of Courts.</p>
      </div>

      <div class="col-xs-6 col-md-3">
        <h6>Categories</h6>
        <ul class="footer-links">
          <li><a href="">Supreme Court</a></li>
          <li><a href="">High Courts</a></li>
          <li><a href="">District Courts</a></li>
          <li><a href="">CONTACT US</a></li>

        </ul>
      </div>

      <div class="col-xs-6 col-md-3">
        <h6>Quick Links</h6>
        <ul class="footer-links">
          <li><a href="">About Us</a></li>
          <li><a href="">Contact Us</a></li>
          <li><a href="">Contribute</a></li>
          <li><a href="">Privacy Policy</a></li>

        </ul>
      </div>
    </div>
    <hr>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-md-8 col-sm-6 col-xs-12">
        <p class="copyright-text">Copyright &copy; 2021
     <a href="#">E-Courts</a>.
        </p>
      </div>

      <div class="col-md-4 col-sm-6 col-xs-12">
        <ul class="social-icons">
          <li><a class="facebook" href="#"><i class="fa fa-facebook"></i></a></li>
          <li><a class="twitter" href="#"><i class="fa fa-twitter"></i></a></li>
        </ul>
      </div>
    </div>
  </div>
</footer>

</body>
</html>
    

court/templates/court/base.html
{% load static %}
<!DOCTYPE html>

    <html lang="en">
      <head>
        <title>E-Courts</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="{% static 'court/style.css' %}">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

        {% if title %}
        <title>ecourt - {{ title }}</title>
        {% else %}
        <title>ecourt</title>
        {% endif %}
      </head>
      <body>
      
      <header class="navbar navbar-inverse navbar-fixed-top bs-docs-nav" role="banner">
        <div class="container">
          <div class="navbar-header">
            <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a href="{% url 'court:home' %}" class="navbar-brand">E-Court</a>
          </div>
          <nav class="collapse navbar-collapse bs-navbar-collapse" role="navigation">
            <ul class="nav navbar-nav navbar-right">
              <li>
                <a href="{% url 'court:home' %}">Home</a>
              </li>
              <li>
                <a href="{% url 'court:about' %}">About </a>
              </li>
              <li>
                <a href="{% url 'court:feecalc' %}">Fee calculator</a>
              </li>
              <li>
                <a href="{% url 'court:status' %}">Check Status</a>
              </li>
              <li >
                <a href="{% url 'court:login' %}">Login</a>
              </li>
              <li >
                <a href="{% url 'court:register' %}">Register</a>
              </li>
            <li >  <div class="wrap">
         </div>
      </div>  </li>
            </ul>
          </nav>
        </div>
      </header><br /><br ><br >    

      <main role="main" class="container">
        <div class="row">
          <div class="col-md-8">
            {% block content %}{% endblock %}
          </div>
        </div>
      </main>

<!-- Site footer -->
<hr><br>
  <footer class="site-footer fix">
    <div class="container">
      <div class="row">
        <div class="col-sm-12 col-md-6">
          <h6>About</h6>
          <p class="text-justify"><i>TOWARDS A DIGITAL INDIA </i> The e-Courts project was conceptualized on the basis of the National Policy and Action Plan for Implementation of information and communication technology in the Indian Judiciary–2005 submitted by e-Committee, with a vision to transform the Indian Judiciary by ICT enablement of Courts.</p>
        </div>

        <div class="col-xs-6 col-md-3">
          <h6>Categories</h6>
          <ul class="footer-links">
            <li><a href="">Supreme Court</a></li>
            <li><a href="">High Courts</a></li>
            <li><a href="">District Courts</a></li>
            <li><a href="">CONTACT US</a></li>

          </ul>
        </div>

        <div class="col-xs-6 col-md-3">
          <h6>Quick Links</h6>
          <ul class="footer-links">
            <li><a href="">About Us</a></li>
            <li><a href="">Contact Us</a></li>
            <li><a href="">Contribute</a></li>
            <li><a href="">Privacy Policy</a></li>

          </ul>
        </div>
      </div>
      <hr>
    </div>
    <div class="container">
      <div class="row">
        <div class="col-md-8 col-sm-6 col-xs-12">
          <p class="copyright-text">Copyright &copy; 2021
       <a href="#">E-Courts</a>.
          </p>
        </div>

        <div class="col-md-4 col-sm-6 col-xs-12">
          <ul class="social-icons">
            <li><a class="facebook" href="#"><i class="fa fa-facebook"></i></a></li>
            <li><a class="twitter" href="#"><i class="fa fa-twitter"></i></a></li>
          </ul>
        </div>
      </div>
    </div>
</footer>

</body>
</html>

court/templates/court/fees.html
{% extends "court/base.html" %}
{% block content %}
    <div class="containercasefile casefilediv" style="background: #025e5c;">
        <h1>Fee calculator</h1>
        <h2>Results</h2>
        <p style="font-size: larger;">
            Court Type : {{court}}<br>
            Case Type : {{case}}<br>
            Case Sub-type : {{subtype}}<br>
        </p>
        <h3>Court Fees : {{fees}}</h3><br>
    </div>
    <br>
    <form id="back" action="{% url 'court:feecalc' %}">
        <input type="submit" value="Calculate for another case" style="background: #025e5c; color: azure; margin-left: 433px; ; font-size: 20px; height: 45px;">
    </form>
{% endblock content %}

court/templates/court/search.html
{% extends "court/base.html" %}
{% block content %}

<br><br><br><br>
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-10">
      <br>
<h2 >Enter CNR number to search</h2><br>
<br><br>

<form  id="cnrsearch" action="{% url 'court:status' cnr %}"  method="POST" >
  {% csrf_token%}
  <input type="text" placeholder="Enter CNR..." name="search" style="color:black">
  <button type="submit" style="background-color: #4c8d8c;"><i class="fa fa-search"></i></button>
</form>

<br><br><br><br><br><br><br><br>

</div></div></div>

{% endblock content %}